name: PHP Composer

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        env:
          MARIADB_RANDOM_ROOT_PASSWORD: yes
          MARIADB_DATABASE: filing_test
          MARIADB_USER: filing
          MARIADB_PASSWORD: "!ChangeMe!"
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install yarn dependencies
      run: yarn install

    - name: build javascript
      run: yarn encore dev

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Setup database create schema
      run: composer run-script create-schema

    - name: Setup database load fixtures
      run: composer run-script load-fixtures

    - name: Run test suite
      run: composer run-script test

    - name: Run mutation testing
      run: composer run-script infection